"""baseline - toan bo schema hien tai

Revision ID: 0001
Revises: 
Create Date: 2026-07-10 10:00:14.389951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('mc_title', sa.String(), nullable=True),
    sa.Column('mc_bio', sa.String(), nullable=True),
    sa.Column('mc_specialties', sa.String(), nullable=True),
    sa.Column('mc_featured', sa.Boolean(), nullable=False),
    sa.Column('is_pro', sa.Boolean(), nullable=False),
    sa.Column('pro_source', sa.String(), nullable=True),
    sa.Column('push_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('genre',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lesson',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('buoi', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('tip', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('brief', sa.JSON(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('admin_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_path',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('genre_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('tickets', sa.Integer(), nullable=False),
    sa.Column('last_day', sa.Date(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('energy_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('rubric_module',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('genre_id', sa.String(), nullable=False),
    sa.Column('wpm_min', sa.Integer(), nullable=False),
    sa.Column('wpm_max', sa.Integer(), nullable=False),
    sa.Column('focus', sa.String(), nullable=False),
    sa.Column('tips', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genre_id')
    )
    op.create_table('level',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('path_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['learning_path.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('level_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_lesson',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('tip', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('brief', sa.JSON(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['content_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clip',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=True),
    sa.Column('content_lesson_id', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_lesson_id'], ['content_lesson.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_request',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clip_id', sa.String(), nullable=False),
    sa.Column('hoc_vien_id', sa.String(), nullable=False),
    sa.Column('mc_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('claimed_by', sa.String(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claimed_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['clip_id'], ['clip.id'], ),
    sa.ForeignKeyConstraint(['hoc_vien_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['mc_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clip_id', sa.String(), nullable=False),
    sa.Column('volume_label', sa.String(), nullable=False),
    sa.Column('speed_wpm', sa.Float(), nullable=False),
    sa.Column('filler_count', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('coverage', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clip.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clip_id')
    )
    op.create_table('mc_review',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('mc_id', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mc_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['review_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('badge_card',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('hoc_vien_id', sa.String(), nullable=False),
    sa.Column('mc_name', sa.String(), nullable=False),
    sa.Column('mc_title', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hoc_vien_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['mc_review.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badge_card')
    op.drop_table('mc_review')
    op.drop_table('score')
    op.drop_table('review_request')
    op.drop_table('clip')
    op.drop_table('content_lesson')
    op.drop_table('content_session')
    op.drop_table('level')
    op.drop_table('rubric_module')
    op.drop_table('progress')
    op.drop_table('learning_path')
    op.drop_table('audit_log')
    op.drop_table('lesson')
    op.drop_table('genre')
    op.drop_table('app_user')
    # ### end Alembic commands ###
