"""content_lesson.sample_voice_key - giong MC mau (P1-4)

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-10 22:41:10.556515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sample_voice_key', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_lesson', schema=None) as batch_op:
        batch_op.drop_column('sample_voice_key')

    # ### end Alembic commands ###
