"""score.passed + fail_reason - cham rot (V4-2)

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-11 21:55:30.884018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passed', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('fail_reason', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('fail_reason')
        batch_op.drop_column('passed')

    # ### end Alembic commands ###
