"""progress: coins/streak_freeze/league/quests - bo may giu chan

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-13 14:24:05.802834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('streak_freezes', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('league_xp', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('league_tier', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('week_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('quests_day', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('quests_claimed', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('streak_pinged_day', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_column('streak_pinged_day')
        batch_op.drop_column('quests_claimed')
        batch_op.drop_column('quests_day')
        batch_op.drop_column('week_start')
        batch_op.drop_column('league_tier')
        batch_op.drop_column('league_xp')
        batch_op.drop_column('streak_freezes')
        batch_op.drop_column('coins')

    # ### end Alembic commands ###
