"""weekly_challenge + challenge_entry (C2)

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-13 14:28:26.910192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_challenge',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenge_entry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('challenge_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('audio_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('likes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('award', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['weekly_challenge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenge_entry')
    op.drop_table('weekly_challenge')
    # ### end Alembic commands ###
