"""progress: misa cosmetics (color/outfit/owned)

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-13 14:55:28.201450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('misa_color', sa.String(), server_default='coral', nullable=False))
        batch_op.add_column(sa.Column('misa_outfit', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('owned_cosmetics', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_column('owned_cosmetics')
        batch_op.drop_column('misa_outfit')
        batch_op.drop_column('misa_color')

    # ### end Alembic commands ###
