"""referral: ref_code/referred_by + ref_rewarded

Revision ID: 0008
Revises: 0007
Create Date: 2026-07-13 15:28:23.899485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0008'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_app_user_ref_code', ['ref_code'])

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_rewarded', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_column('ref_rewarded')

    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_app_user_ref_code', type_='unique')
        batch_op.drop_column('referred_by')
        batch_op.drop_column('ref_code')

    # ### end Alembic commands ###
